### ISSUE TITLE
archive doesn't contain teamcity-plugin.xml file

### ISSUE THREAD

**Issue by renperez** [jfrog/teamcity-artifactory-plugin#46]
archive doesn't contain teamcity-plugin.xml file using the latest build. 2.6.0. This is the error I get when uploading the zip file to Teamcity

**Comment by renperez** [comment]
TeamCity Professional 2017.2.4 (build 51228)

**Comment by casz** [comment]
Should be fixed by #47

**Comment by DimaNevelev** [comment]
@renperez 
Our latest release of the plugin ([2.7.1](https://bintray.com/jfrog/jfrog-jars/teamcity-artifactory-plugin/2.7.1)) Includes @casz 's fix.
Please confirm it fixes the issue.
