### ISSUE TITLE
Missing license in repository

### ISSUE THREAD

**Issue by FredDeschenes** [jfrog/teamcity-artifactory-plugin#68]
Hi!

[This page](https://www.jfrog.com/confluence/display/RTF/TeamCity+Artifactory+Plug-in) mentions that the plugin is available under the Apache 2 license, but there is nothing in the repository that mentions that. Would it be possible to add a license file to the repository to make this clearer?

**Comment by casz** [comment]
Since Apache 2 license text doesn't change, you can perhaps send it as a pull request instead of an issue? 😅 
Hint copy it from here: https://github.com/jfrog/ide-plugins-common/blob/master/LICENSE

**Comment by eyalbe4** [comment]
I've just added it.
Thanks @FredDeschenes and @casz.

**Comment by casz** [comment]
@eyalbe4 you're too nice 😆

**Comment by FredDeschenes** [comment]
Thanks everyone!
