### ISSUE TITLE
Artifactory properties are not saved with version 2.9.0

### ISSUE THREAD

**Issue by mas2020** [jfrog/teamcity-artifactory-plugin#94]
Hi,
I have this parameter set on a TeamCity build configuration:
```
artifactory.deploy.extension.Type
```
with the version **_2.7.1_** of the plugin, the property `extension.Type` is correctly saved on Artifactory after deploying an artifact. Installing the version **_2.9.0_**, the artifact is pushed correctly into Artifactory but the custom properties are not set anymore.
Thanks in advance for checking the possible reasons.

**Comment by yahavi** [comment]
@mas2020,
Thanks for reporting this issue.
Could you please elaborate more about your build? Which type of build is it? Generic? Maven? Gradle? etc...
Could you please also check if this issue resolved in the latest version, 2.9.1?

**Comment by mas2020** [comment]
Hi @yahavi,
It is a generic build (runner type = Comman Line) where I activated Artifactory integration since the 2.6.0 version of your plugin.
Sure, I will take a look at 2.9.1 as soon as I can.
Thanks for the immediate reply.

**Comment by mas2020** [comment]
Hi @yahavi,
I tried with 2.9.1 version and unfortunately it doesn't work. I reverted on 2.7.1 and now works again.
Please, let me know, in case of any news, thanks.

**Comment by mas2020** [comment]
Hi @yahavi,
any news related to this issue? I confirm that I needed to downgrade to the v2.7.1 that seems to be the last version working when saving custom properties to Artifactory.

Thanks

**Comment by mas2020** [comment]
Any update on this topic?
For us it represents a blocking issue in our pipeline, since:
* with version 2.7.1 we have more and more failures in terms of builds with Gradle 7
* with version 2.9.x, when publishing from TeamCity to Artifactory, we lose metadata that are vital in our release processes and are expected to be correctly published too, since prefixed with artifactory.deploy.:
    * artifactory.deploy.build.parentNumber
    * artifactory.deploy.extension.Type
    
Thanks

**Comment by talarian1** [comment]
Hi @mas2020,
Sorry for the inconvenience this issue caused.
TeamCity Artifactory plugin 2.9.4 has been released and should fix this issue.
We will appreciate any feedback from you.
